# For GIST dataset
mean:
  type: float
  log: false
  lower: -800
  upper: -300
  prior: -450
  prior_confidence: "low"

std:
  type: float
  log: true
  lower: 250
  upper: 800
  prior: 550
  prior_confidence: "low"
