voxel_calculation:
  type: categorical
  choices: ["mean", "median", "isotropic", "volumetric_isotropic"]
  
number_of_epochs:  # for multifidelity
  type: int
  lower: 99
  upper: 100
  is_fidelity: true  # explicitly marked as fidelity parameter
