weight_decay:
  type: float
  log: true
  lower: 1e-6
  upper: 1e-2
  default: 1e-4
  default_confidence: "medium"
  
number_of_epochs:  # for multifidelity
  type: int
  lower: 99
  upper: 100
  is_fidelity: true  # explicitly marked as fidelity parameter
