# DenseNet 3D hyperparameters 
init_features:
  type: int
  lower: 16
  upper: 64

bn_size:
  type: int
  lower: 1
  upper: 4

growth_rate:
  type: int
  lower: 12
  upper: 32

num_layers_block1:
  type: int
  lower: 4
  upper: 12

num_layers_block2:
  type: int
  lower: 8
  upper: 24

num_layers_block3:
  type: int
  lower: 16
  upper: 48
  
num_layers_block4:
  type: int
  lower: 8
  upper: 24

conv0_stride:
  type: int
  lower: 1
  upper: 3

dropout_rate:
  type: float
  log: false
  lower: 0.0
  upper: 0.5
