voxel_calculation:
  type: categorical
  choices: ["mean", "median", "isotropic", "volumetric_isotropic"]

learning_rate:
  type: float
  log: true
  lower: 1e-5
  upper: 1e-1

gradient_accumulation_steps: 
  type: int
  lower: 5
  upper: 10
  
optimizer_type:
  type: categorical
  choices: ["adam", "adamw", "sgd"]

weight_decay:
  type: float
  log: true
  lower: 1e-6
  upper: 1e-2

warmup_epochs:
  type: int
  lower: 0
  upper: 10

label_smoothing:
  type: float
  log: false
  lower: 0.0
  upper: 0.2

mixup_alpha:
  type: float
  log: false
  lower: 0.0
  upper: 1.0

# NOTE: Batch size is fixed to 1 and will not be part of the search space
# batch_size:
#   type: int
#   lower: 2
#   upper: 32