#------------------------------------------------------------------------------
# Core Experiment Settings
#------------------------------------------------------------------------------
hydra:
  output_subdir: null
  run:
    dir: ${experiment_base_dir}/hydra_output

seed: 42
experiment_base_dir: experiments/${run_mode}/${data.dataset}/${experiment_dir_suffix}
experiment_dir_suffix: ${experiment_name}/seed_${seed}
neps_directory: ${experiment_base_dir}/NePS_output
quicktune_directory: ${experiment_base_dir}/QuickTune_output
experiment_name: test
run_mode: NePS  # Options: 'NePS', 'QuickTune', 'Baseline', 'Portfolio'
developer_mode: false
cv_outer_folds_repeats: 5   # Number of repetitions for repeated stratified K-fold for outer folds for cross-validation: train_val/test splits
cv_outer_folds_splits: 3    # Number of splits per repetition forouter folds for cross-validation: train_val/test splits
cv_inner_folds: 5           # Number of inner folds for cross-validation: train/val splits

#------------------------------------------------------------------------------
# Training Configuration
#------------------------------------------------------------------------------
training:
  number_of_epochs: 50   # Total number of training epochs (for non-multi-fidelity searchspaces)
  early_stopping: True   # Whether to use early stopping
  patience: 20            # Number of epochs with no improvement after which training will be stopped
  use_loss_threshold: True  # Whether to use loss threshold to stop training

#------------------------------------------------------------------------------
# QuickTune Optimization Settings
#------------------------------------------------------------------------------
qt:
  use_medical_portfolio: true
  use_custom_metafeat_extraction: true  # TODO: delete this, but keep it for now as a reference
  use_quick_image_cls_tuner: true
  use_custom_objective: true
  use_ftpfn_perf_predictor: true

#------------------------------------------------------------------------------
# NePS Optimization Settings
#------------------------------------------------------------------------------
pipeline_space: configs/pipeline_spaces/pipeline_space_without_user_priors.yaml
max_evaluations: 10       # Maximum number of configurations to evaluate
metric: auc                # Metric to optimize: 'auc' (default), 'f1', 'accuracy', 'precision', or 'recall'
searcher: random_search       # Options: 'default', 'bayesian_optimization', 'random_search', 'hyperband', 'priorband', 'mobster', 'asha', 'regularized_evolution'

#------------------------------------------------------------------------------
# Model Architecture
#------------------------------------------------------------------------------
model:
  type: resnet            # Model architecture type
  task: classification    # Type of machine learning task

#------------------------------------------------------------------------------
# Dataset Configuration
#------------------------------------------------------------------------------
data:
  dimensionality: 2d      # Dimension of the dataset
  dataset: brain_tumor    # Name of the dataset
  path: datasets          # Path to the dataset
  debug_mode: False       # Enable/disable debug mode
  num_workers: 4          # Number of parallel data loading workers
  augmentation_type: basic   # Type of augmentation to use ('basic''medical' or 'trivial')
  cache_data: True        # Whether to preload the data into memory
  use_smart_preprocessing: True  # Whether to apply Natalia's smart preprocessing (3D only)
  voxel_calculation: all  # Voxel calculation method: 'mean', 'median', 'isotropic', 'volumetric_isotropic', or 'all'

#------------------------------------------------------------------------------
# Experiment Monitoring & Checkpointing
#------------------------------------------------------------------------------
logging:
  eval_every: 1           # Evaluate model every N epochs
  save_every: 100         # Save model checkpoint every N epochs
  viz_images_every: 100   # Save TensorBoard images every N epochs for visualization

#------------------------------------------------------------------------------
# Portfolio Creation Settings
#------------------------------------------------------------------------------
merge_runs: true  # Set to true when merging multiple runs
experiment_names: "test"  # Comma-separated list of experiment names to merge
seeds: "42"  # Comma-separated list of seeds to merge
base_dir: experiments/NePS/${data.dataset}
portfolio_dir: experiments/Portfolio
