# @package hydra

# Configure output path for Hydra logs
run:
  dir: ${experiment_base_dir}/hydra_output

# Configure logging to the hydra_output folder
job_logging:
  handlers:
    file:
      class: logging.FileHandler
      mode: w
      formatter: colorlog
      filename: ${hydra.runtime.output_dir}/train.log

  root:
    handlers: [console, file]

hydra_logging:
  handlers:
    file:
      class: logging.FileHandler
      mode: w
      formatter: colorlog
      filename: ${hydra.runtime.output_dir}/hydra.log

  root:
    handlers: [console, file]

# Prevent creation of the outputs/ directory
output_subdir: null 