#------------------------------------------------------------------------------
# Core Experiment Settings
#------------------------------------------------------------------------------
hydra:
  output_subdir: null
  run:
    dir: ${experiment_base_dir}/hydra_output

seed: 42
experiment_base_dir: experiments/${data.dataset}/${experiment_name}/seed_${seed}
root_directory: ${experiment_base_dir}/NePS_output
experiment_name: test_desmoid
developer_mode: false

#------------------------------------------------------------------------------
# QuickTune Settings
#------------------------------------------------------------------------------
portfolio_dir: experiments/portfolio
use_medical_portfolio: true

#------------------------------------------------------------------------------
# NePS Optimization Settings
#------------------------------------------------------------------------------
pipeline_space: configs/pipeline_spaces/pipeline_space_without_user_priors.yaml
max_evaluations: 10       # Maximum number of configurations to evaluate
metric: f1                # Metric to optimize: 'f1' (default), 'accuracy', 'precision', or 'recall'
searcher: hyperband       # Options: 'default', 'bayesian_optimization', 'random_search', 'hyperband', 'priorband', 'mobster', 'asha', 'regularized_evolution'

#------------------------------------------------------------------------------
# Model Architecture
#------------------------------------------------------------------------------
model:
  type: resnet            # Model architecture type
  task: classification    # Type of machine learning task

#------------------------------------------------------------------------------
# Dataset Configuration
#------------------------------------------------------------------------------
data:
  dimensionality: 2d      # Dimension of the dataset
  dataset: brain_tumor    # Name of the dataset
  path: datasets          # Path to the dataset
  debug_mode: False       # Enable/disable debug mode
  num_workers: 4          # Number of parallel data loading workers
  augmentation_type: medical   # Type of augmentation to use ('medical' or 'trivial')
  k_folds: 5              # Number of folds for K-Fold Cross Validation
  preload_data: True      # Whether to preload the data into memory

#------------------------------------------------------------------------------
# Experiment Monitoring & Checkpointing
#------------------------------------------------------------------------------
logging:
  eval_every: 1           # Evaluate model every N epochs
  save_every: 100         # Save model checkpoint every N epochs
  viz_images_every: 100   # Save TensorBoard images every N epochs for visualization
